I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 203, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 446, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 446, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 456, in _execute_python_hide
    renpy.load("_reload-2")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\bootstrap.py", line 313, in bootstrap
    renpy.main.main()
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\main.py", line 513, in main
    run(restart)
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\main.py", line 139, in run
    renpy.execution.run_context(True)
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\execution.py", line 876, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 203, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 446, in script
    python hide:
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\ast.py", line 881, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00keymap.rpy", line 446, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 456, in _execute_python_hide
    renpy.load("_reload-2")
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\loadsave.py", line 730, in load
    log.unfreeze(roots, label="_after_load")
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\python.py", line 1868, in unfreeze
    self.rollback(0, force=True, label=label, greedy=greedy, on_load=True)
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\python.py", line 1696, in rollback
    raise Exception("Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
chadisland 1.0
Sun Dec 02 09:18:01 2018
